'use client';
import {useMemo,useState} from 'react';
import {Search,MapPin,SlidersHorizontal,ShieldCheck,Clock3,HeartHandshake} from 'lucide-react';
import Header from '../components/Header';
import VetCard from '../components/VetCard';
import {vets} from '../lib/vets';

const filters=['Open now','Home visits','English-speaking','Emergency','Exotic pets','Parking'];
export default function Home(){
 const [query,setQuery]=useState(''); const [active,setActive]=useState('');
 const shown=useMemo(()=>vets.filter(v=>{const q=query.toLowerCase();const match=!q||`${v.name} ${v.area} ${v.tags.join(' ')} ${v.languages.join(' ')}`.toLowerCase().includes(q);const f=!active||(active==='Open now'?v.open:active==='English-speaking'?v.languages.includes('English'):active==='Parking'?v.parking.toLowerCase().includes('parking'):v.tags.includes(active));return match&&f}),[query,active]);
 return <main><div className="top"><Header/><section className="hero"><div className="hero-copy"><p className="kicker">VETERINARY CARE, MADE CLEAR</p><h1>The right vet.<br/><em>Right when you need one.</em></h1><p>Compare trusted clinics by services, access, languages and pricing—without making five phone calls first.</p></div><div className="hero-art"><div className="pet-orbit"><span className="pet">🐕</span><b>Verified details</b></div><span className="float one">Open now</span><span className="float two">English spoken</span><span className="float three">From €25</span></div></section>
 <section className="search-wrap"><div className="searchbar"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Area, clinic, service or animal"/><span></span><MapPin/><input placeholder="Athens"/><button>Search</button></div><div className="quick">{filters.map(f=><button className={active===f?'active':''} onClick={()=>setActive(active===f?'':f)} key={f}>{f}</button>)}<button><SlidersHorizontal size={15}/> All filters</button></div></section></div>
 <section className="results" id="clinics"><div className="section-title"><div><p className="kicker">CURATED FOR ATHENS</p><h2>Clinics that fit your life</h2></div><p>{shown.length} clinics shown</p></div><div className="grid">{shown.map(v=><VetCard key={v.slug} vet={v}/>)}</div>{!shown.length&&<div className="empty">No clinics match yet. Try another area or filter.</div>}</section>
 <section className="why" id="how"><div><p className="kicker">MORE THAN A PIN ON A MAP</p><h2>Know before you go.</h2></div><div className="why-grid"><article><ShieldCheck/><h3>Details you can trust</h3><p>See what was supplied by the clinic, verified by FindAVet, and when it was last checked.</p></article><article><Clock3/><h3>Practical information</h3><p>Parking, transport, languages, home visits and opening status—visible before you call.</p></article><article><HeartHandshake/><h3>Made for pet owners</h3><p>Compare the things that actually matter when your pet needs care, without the clutter.</p></article></div></section>
 <footer><div className="brand"><span className="brandmark">+</span>findavet<span>.</span></div><p>Helping Athens pet owners find care with confidence.</p><small>Demo clinic information is fictional.</small></footer></main>}
